services:
  - type: web
    name: dhyaan-chakra-api
    runtime: node
    buildCommand: npm install && cd server && npm install
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /
    autoDeploy: true
    domains:
      - dhyaan-chakra-api.onrender.com
    pullRequestPreviewsEnabled: false
